#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Yunier Alvarez"
email = "yunieralvarez@gmail.com"

[ui]
editor = "hx"
pager = "cat"
default-revset = "all()"
default-command = "log"
